### PR TITLE
Feature/update links commands

### PR DESCRIPTION
**Pull request by carlosazaustre**
### Describe in detail the problem you had and how this PR fixes it
Updated download links and added tar command to extract the files.
Also, I added the command for 

### Is there an open issue you can link to?
None

### CODE REVIEW

**Comment by NGTmeaty** [comment]
For the download link, I believe we'll want to show users to the latest version.

**Comment by illiapoplawski** [comment]
A copy/paste command for downloading the latest linux release is: 
curl -s https://api.github.com/repos/codercom/code-server/releases/latest | grep "browser_download_url.*code-server-.*darwin-x64\.zip" | cut -d '"' -f 4 | wget -O ~/code-server-linux -qci -

tar -xzvf coder-server-linux.zip -C ~/code-server-linux

Would make it easier for people to download without needing to manually edit the commands

**Comment by NGTmeaty** [comment]
I do like what @illiapoplawski posted. From short amount of research I've done, the one posted above does seem to be the most streamlined approach to getting the latest release. 

edit: looking into this a bit more, looks like we agreed on /releases/latest at #130

**Comment by illiapoplawski** [comment]
@NGTmeaty #130 and my command both use /releases/latest however #130 requires the user to manually enter the version to download.  My command automatically grabs the latest version requiring no editing of the command by the user

**Comment by NGTmeaty** [comment]
Yup I saw. I was just pointing out the consensus we reached last time.

**Comment by kylecarbs** [comment]
There's a merge conflict to fix. Once fixed, I'd be happy to merge.

**Pull request merged**
