### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by tacyarg**
Very basic implementation of a docker file, would need some optional arguments to support the certs

### CODE REVIEW

**Comment by sakanamax** [comment]
I try to build it with docker image.
and try to 
# docker run -d -p 9000:9000  image_name 
when I connect http://localhost:9000
It just show wait for reply .....

**Comment by cyalide** [comment]
@sakanamax I can confirm the same behavior.

**Comment by jwm** [comment]
Adding `net-tools` to the installed package list fixes this for me -- https://github.com/codercom/code-server/blob/master/packages/server/src/portScanner.ts needs `netstat`.

**Comment by kylecarbs** [comment]
Closed in favor of https://github.com/codercom/code-server/pull/57. Feel free to make any touchups beyond that!

**Pull request closed without merging**
