### PR TITLE
add Simplified Chinese translation for README

### PR DESCRIPTION
**Pull request by weditor**
add Simplified Chinese README

### CODE REVIEW

**Comment by Aaaaash** [comment]
@weditor 😀 中英文之间空格, 以及专有名词 Windows/Mac 这些单词大小写好像有点问题, 只是提个建议...

**Comment by weditor** [comment]
@Aaaaash 第一次翻译，不清楚这些，见笑了。:smile:

**Comment by weditor** [comment]
https://github.com/codercom/code-server/issues/47

It seems that they want to move these documents to somewhere else.

**Comment by jeasonstudio** [comment]
我认为现在还不是做文档本地化的最好时机，至少要等到项目的基础文档稳定下来，目前还远远不够。  
I don't think it's the best time to do document localization. At least until the basic documentation of the project has stabilized.

**Comment by weditor** [comment]
#50

I would like to close this pull request.
I'll keep an eye on this project. I may open another pr if you still need document translation in the future,

**Pull request closed without merging**
