### PR TITLE
Significantly improve the Dockerfile

### LINKED ISSUE #65: sudo in Dockerfile?
See https://github.com/codercom/code-server/pull/57#discussion_r263202554

### LINKED ISSUE #361: docker one-liner should use the -i flag
Otherwise signals aren't passed correctly and the container keeps running in the bg.

Also, we need to make code-server handle signals correctly.

### LINKED ISSUE #383: Use a tinyinit in the dockerfile
Will make ctrl+c work.

### LINKED ISSUE #403: Error: EACCES: permission denied
```
[root@localhost ~]# docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth
Unable to find image 'codercom/code-server:latest' locally
Trying to pull repository docker.io/codercom/code-server ... 
latest: Pulling from docker.io/codercom/code-server
e58ad9fd24ca: Pull complete 
0a4c669d2dea: Pull complete 
ab60767ef52b: Pull complete 
8cc3b738fbea: Pull complete 
4a49f00acafc: Pull complete 
15aff5fdd28f: Pull complete 
1a344d81f432: Pull complete 
f079d5b4236e: Pull complete 
Digest: sha256:d96615907185d67fcc75655eef3eee28399efb968aaa5e1dc319fa064db3fb08
Status: Downloaded newer image for docker.io/codercom/code-server:latest
ERROR { Error: EACCES: permission denied, mkdir '/root/project/code-server'
  [stack]: 'Error: EACCES: permission denied, mkdir \'/root/project/code-server\'',
  [message]: 'EACCES: permission denied, mkdir \'/root/project/code-server\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/root/project/code-server' }
free(): invalid pointer

```

### LINKED ISSUE #404: Switch to an LTS version of Ubuntu (18.04) for the Dockerfile
Today, the Dockerfile points to Ubuntu 18.10. For best compatibility, and for the best support long term, it would be better to use an LTS version of Ubuntu like 18.04 for better support overall.

cc @jaykul

### PR DESCRIPTION
**Pull request by nhooyr**
- Adds dumb-init so closes #407, closes #361, closes #383
- User mode docker so closes #192, closes #65
- Uses latest docker ubuntu instead of 18.10 which is the rolling tag so
closes #404

Thanks to @RichardMcSorley and @sr229

### Is there an open issue you can link to?

### CODE REVIEW

**Comment by nhooyr** [comment]
Will need to update the README.md with a command to mount into `/home/coder/project`.

**Comment by nhooyr** [comment]
Unfortunately, dumb-init is not sending signals properly when using the `-t` option to docker so I'm not sure what's going on.

**Comment by nhooyr** [comment]
Nvm, got it working. See https://stackoverflow.com/questions/41097652/how-to-fix-ctrlc-inside-a-docker-container

**Comment by RichardMcSorley** [comment]
@nhooyr Great you got it working.

**Comment by frol** [comment]
Passwordless sudo is like an always-open door (in the real world). There is definitely a room for improvement.

**Comment by sr229** [comment]
@frol its still teaching basic practice anyways, so I don't think primarily its open door especially if its just a container (and the fact GCP practices this as well due to the fact - you know, they're SSH keys only by default).

**Comment by nhooyr** [comment]
We could prompt users to set a password on startup later @frol but for now this is a simple improvement.

**Comment by sr229** [comment]
I vote against that IMHO, I don't think we need to support that kind of use case especially in Docker. The user should do it themselves if they really want to. We just provide a sane default for them.

**Comment by nhooyr** [comment]
Asking for a password is a safe default and the common use case. What we're providing is the exception.

**Pull request merged**
