### PR TITLE
fix Dockerfile

### PR DESCRIPTION
**Pull request by yush1ga**
Thanks for making this awesome soft open source.

Unfortunately, `Dockerfile` doesn't work in my environment.
It may depend on os arch environment.

I tried to fix it by tweaking `Dockerfile`.

### CODE REVIEW

**Comment by nhooyr** [comment]
Could you elaborate on the error/issue you were having? I don't see what this fixes.

**Comment by coderasher** [comment]
Ah, probably because I added the architecture to the binary name here: https://github.com/codercom/code-server/commit/994531d8bbfa62d849b65a5828f87f3b4c8983fa#diff-09fded6ea343c3bb08cac161ed7a3cbaR17

**Comment by nhooyr** [comment]
Dammit Asher. I'll push a fix for this. Thanks for pointing this out @yush1ga

**Comment by nhooyr** [comment]
See #109

**Comment by yush1ga** [comment]
@nhooyr @coderasher Thanks!

**Pull request closed without merging**
