### PR TITLE
Clone exact vscode release branch when build task

### PR DESCRIPTION
**Pull request by jeasonstudio**
### Describe in detail the problem you had and how this PR fixes it

Build toooo slow.

### CODE REVIEW

**Comment by kylecarbs** [comment]
I believe the release is 1.32.0

**Comment by nhooyr** [comment]
This broke local builds.

**Comment by nhooyr** [comment]
Because the checkout was removed.

**Comment by kylecarbs** [comment]
Ah. We can revert this.

**Comment by kylecarbs** [comment]
A bit confused how the CI passed

**Comment by nhooyr** [comment]
CI clones every time the exact release after this PR. When we try and reuse the existing lib/vscode directory, this PR makes it not checkout the exact release.e

**Comment by nhooyr** [comment]
Will include fix in my upcoming PR.

**Pull request merged**
