### PR TITLE
Dockerfile: cleanup and add en_US.UTF-8 locale

### LINKED ISSUE #83: Locales are not available in local docker image
- `code-server` version: master
- OS Version:  4.20.8-arch1-1-ARCH

not having locales can cause unexpected behaviour when working with text that is utf-8 encoded

#### Steps to Reproduce

1. docker run -p 8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth
2. open terminal and type `locale -a` see `en_US.UTF-8 is` missing

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #84
Closes #83

Thanks @xMrWhite, @frol and @sr229.

### CODE REVIEW

**Comment by nhooyr** [comment]
CI failures are related to rate limits so merging this anyway. @kylecarbs is this a known issue?

**Comment by kylecarbs** [comment]
Yup its known. I've attempted to find a good solution. Might need to jank within the CI.

**Comment by Omeryl** [comment]
@kylecarbs unrelated to this issue, but I didn't see another one referencing that problem:

have you tried using travis-ci's caching mechanism? it'd reduce the number of calls your throwing to NPM I believe.

https://docs.travis-ci.com/user/caching/ is the full documentation.

It is generally as simple as adding this to your ci file: `cache: npm`

**Comment by kylecarbs** [comment]
Hmm. Will add this. Thanks @Omeryl !

**Pull request merged**
