### PR TITLE
Removed files that are in .gitignore but still in the tree

### PR DESCRIPTION
**Pull request by MOZGIII**
### Describe in detail the problem you had and how this PR fixes it
I'm doing the packing for debian, and I found out there are somes that are in the `.gitignore` (`git clean -Xdf` removes them) but they're in the tree. It cases some problems for the way I'm trying to package things.
Those files were probably added by mistake, so this PR removes them.

### Is there an open issue you can link to?
Not that I'm aware of.

### CODE REVIEW

**Comment by code-asher** [comment]
These are part of the `requirefs` tests and shouldn't be removed. We should probably un-ignore the `lib` folder there. We do that for `lib/node_modules` but not `lib`: https://github.com/codercom/code-server/blob/master/packages/requirefs/test/.gitignore#L1

We could also rename `lib` to something else.

**Comment by MOZGIII** [comment]
I'm closing this PR then. At which level do you prefer them ignored?

**Comment by code-asher** [comment]
I think it'd actually be better to rename the directory.

**Comment by MOZGIII** [comment]
Is the pattern in this repo to ignore all the `lib` dirs? Or maybe it should be `/lib` instead of `lib` at the top level?

**Comment by code-asher** [comment]
Ah, that's a good point, we could just ignore `/lib` at the top level. That sounds good to me.

**Pull request closed without merging**
